### ISSUE TITLE
Recent nightly: syntax::ast::ExprKind issue

### ISSUE THREAD

**Issue by MarkSwanson** [frehberg/rust-bytestool#1]
error: no associated item named `Vec` found for type `syntax::ast::ExprKind` in the current scope
   --> /home/maswanso/.cargo/registry/src/github.com-1ecc6299db9ec823/bytestool-0.2.0/src/lib.rs:125:10
    |
125 |         &ast::ExprKind::Vec(ref v) => return extract_vec_from_vec(cx, sp, &(*v).clone()),
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by frehberg** [comment]
Thanks for the notice, I will take a look at it and fix it. Please can u tell me , which version of rust did you observe this first?

**Comment by frehberg** [comment]
Issue has been fixed with  'bytestool v0.3', adapting to modified internal Abstract Syntax Tree (AST)

**Comment by MarkSwanson** [comment]
Sorry for the slow reply.
Thanks for the fix.
